apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-react-app
  template:
    metadata:
      labels:
        app: django-react-app
    spec:
      containers:
        - name: backend
          image: backend_image:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: database-credentials